//! Download normalization logic.
//!
//! This module is responsible for taking a freshly downloaded audio file
//! (typically from yt-dlp) and deterministically placing it into the
//! canonical music library structure.
//!
//! Design constraints:
//! - No UI logic
//! - No AppState access
//! - No network access
//! - Filesystem is the source of truth
//! - Deterministic behavior (no guesses)

use ::std::fs;
use std::path::{Path, PathBuf};

use crate::metadata;
use crate::metadata::parse::{extract_release_year, extract_track_number, extract_youtube_id};
use crate::metadata::write::write_clean_tags;

/// High-level classification of a downloaded track.
///
/// This determines how the track is normalized and where it is placed
/// in the filesystem.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TrackKind {
    /// Auto-generated album track
    ///
    /// Identified by trusted "Provided to YouTube by ..."
    /// or "Auto-generated by YouTube" markers.
    AutoGeneratedAlbum,

    /// Official audio release (single, visualizer, lyric video, etc.)
    OfficialAudioSingle,

    /// Official music video
    OfficialVideo,

    /// Creator / promotional / unknown upload
    CreatorUpload,
}

/// Result of normalizing a downloaded track.
///
/// This struct describes the *final, canonical* interpretation
/// of the track after metadata normalization.
#[derive(Debug, Clone)]
pub struct NormalizedTrack {
    pub artist: String,
    pub album: Option<String>,
    pub title: String,
    pub featured_artists: Vec<String>,

    pub track_number: Option<u32>,
    pub year: Option<u32>,

    pub kind: TrackKind,
    pub youtube_id: String,

    /// Final absolute path on disk after normalization.
    pub final_path: PathBuf,
}

/// Normalize a freshly downloaded track into the canonical library structure.
///
/// Responsibilities (implemented in later steps):
/// - Read embedded metadata
/// - Classify track kind
/// - Normalize artist / title / features
/// - Determine final destination directory
/// - Move and rename the file
///
/// This function performs **no downloads** and **no UI updates**.
pub fn normalize_downloaded_track(
    path: &Path,
    library_root: &Path,
) -> std::io::Result<NormalizedTrack> {
    // Step 1: extract metadata
    let meta = metadata::extract_metadata(path).ok_or_else(|| {
        std::io::Error::new(
            std::io::ErrorKind::InvalidData,
            "failed to extract metadata",
        )
    })?;

    // Step 2: extract stable identifiers
    let youtube_id = extract_youtube_id(&meta, path).ok_or_else(|| {
        std::io::Error::new(std::io::ErrorKind::InvalidData, "missing YouTube ID")
    })?;

    let track_number = extract_track_number(&meta, path);
    let year = extract_release_year(&meta);

    // Step 3: classify track kind
    let kind = classify_track(&meta);

    // NOTE:
    // Everything below this point (normalization, filesystem ops)
    // is implemented in later steps.
    let _ = library_root;

    // unimplemented!("classification complete: kind={kind:?}, track={track_number:?}, year={year:?}");
    let (artist, mut featured_artists) = normalize_artist(&meta.artist, &meta.title);
    let (title, title_features) = normalize_title_and_features(&meta.title);
    featured_artists.extend(title_features);

    let final_path = compute_destination_path(
        library_root,
        &artist,
        meta.album.as_deref(),
        &title,
        &featured_artists,
        kind,
        year,
        track_number,
    );

    // Ensure parent directories exist
    if let Some(parent) = final_path.parent() {
        std::fs::create_dir_all(parent)?;
    }

    // Perform the move
    move_file(path, &final_path)?;

    write_clean_tags(
        &final_path,
        &NormalizedTrack {
            artist: artist.clone(),
            album: meta.album.clone(),
            title: title.clone(),
            featured_artists: featured_artists.clone(),
            track_number,
            year,
            kind,
            youtube_id: youtube_id.clone(),
            final_path: final_path.clone(),
        },
    )?;

    Ok(NormalizedTrack {
        artist,
        album: meta.album.clone(),
        title,
        featured_artists,
        track_number,
        year,
        kind,
        youtube_id,
        final_path,
    })
}

fn classify_track(meta: &crate::metadata::model::TrackMetadata) -> TrackKind {
    let album_present = meta
        .album
        .as_deref()
        .map(|a| !a.trim().is_empty())
        .unwrap_or(false);

    let marker_text = meta
        .comment
        .as_deref()
        .or(meta.synopsis.as_deref())
        .unwrap_or("");

    // Trusted auto-generated album markers
    if album_present
        && (marker_text.contains("Provided to YouTube by")
            || marker_text.contains("Auto-generated by YouTube"))
    {
        return TrackKind::AutoGeneratedAlbum;
    }

    let title = meta.title.to_lowercase();

    if contains_any(
        &title,
        &["official audio", "visualizer", "lyric video", "lyrics"],
    ) {
        return TrackKind::OfficialAudioSingle;
    }

    if contains_any(&title, &["official video", "music video", " mv "]) {
        return TrackKind::OfficialVideo;
    }

    TrackKind::CreatorUpload
}

fn contains_any(haystack: &str, needles: &[&str]) -> bool {
    needles.iter().any(|n| haystack.contains(n))
}

fn normalize_artist(raw: &str, title: &str) -> (String, Vec<String>) {
    let raw = raw.trim();

    if raw.ends_with("Music") {
        if let Some(artist) = extract_artist_from_title(title) {
            return (artist, Vec::new());
        }
    }

    (raw.to_string(), Vec::new())
}

fn extract_artist_from_title(title: &str) -> Option<String> {
    let parts: Vec<_> = title.splitn(2, " - ").collect();
    if parts.len() == 2 && !parts[0].trim().is_empty() {
        Some(parts[0].trim().to_string())
    } else {
        None
    }
}

fn normalize_title_and_features(raw: &str) -> (String, Vec<String>) {
    let mut title = raw.to_string();
    let mut features = Vec::new();

    // Strip leading "Artist - " if present
    if let Some((_, rest)) = title.split_once(" - ") {
        title = rest.to_string();
    }

    // (feat. X), (ft. X)
    if let Some((clean, feats)) = extract_features(&title, "feat.") {
        title = clean;
        features.extend(feats);
    }
    if let Some((clean, feats)) = extract_features(&title, "ft.") {
        title = clean;
        features.extend(feats);
    }

    // (with X, Y & Z)
    if let Some((clean, feats)) = extract_features(&title, "with") {
        title = clean;
        features.extend(feats);
    }

    // Strip junk suffixes AFTER feature extraction
    title = strip_junk_suffixes(&title);

    (title.trim().to_string(), dedup(features))
}

fn extract_features(title: &str, keyword: &str) -> Option<(String, Vec<String>)> {
    let lower = title.to_lowercase();
    let key = format!("({}", keyword);

    let start = lower.find(&key)?;
    let end = lower[start..].find(')')? + start;

    let inside = &title[start + key.len() + 1..end];
    let artists = split_artists(inside);

    let mut cleaned = String::new();
    cleaned.push_str(title[..start].trim_end());
    cleaned.push_str(title[end + 1..].trim_start());

    Some((cleaned, artists))
}

fn split_artists(s: &str) -> Vec<String> {
    s.split(|c| c == ',' || c == '&')
        .map(|a| a.trim())
        .filter(|a| !a.is_empty())
        .map(|a| a.to_string())
        .collect()
}

fn strip_junk_suffixes(title: &str) -> String {
    let junk = ["official video", "official audio", "visualizer", "lyrics"];

    let mut t = title.to_string();

    loop {
        let lower = t.to_lowercase();
        let mut removed = false;

        for j in junk {
            let pat = format!("({})", j);
            let pat2 = format!("[{}]", j);

            if lower.ends_with(&pat) {
                t = t[..t.len() - pat.len()].trim().to_string();
                removed = true;
            } else if lower.ends_with(&pat2) {
                t = t[..t.len() - pat2.len()].trim().to_string();
                removed = true;
            }
        }

        if !removed {
            break;
        }
    }

    t
}

fn dedup(list: Vec<String>) -> Vec<String> {
    let mut out = Vec::new();
    for a in list {
        if !out.iter().any(|x: &String| x.eq_ignore_ascii_case(&a)) {
            out.push(a);
        }
    }
    out
}

fn compute_destination_path(
    library_root: &Path,
    artist: &str,
    album: Option<&str>,
    title: &str,
    featured: &[String],
    kind: TrackKind,
    year: Option<u32>,
    track_number: Option<u32>,
) -> PathBuf {
    let mut path = library_root.join(sanitize_component(artist));

    match kind {
        TrackKind::AutoGeneratedAlbum if album.is_some() => {
            let album_name = album.unwrap();
            let album_dir = match year {
                Some(y) => format!("{y} - {}", album_name),
                None => album_name.to_string(),
            };

            path = path.join(sanitize_component(&album_dir));

            let filename = match track_number {
                Some(n) => format!("{:02}. {}", n, title),
                None => title.to_string(),
            };

            path.join(format!("{}.opus", sanitize_component(&filename)))
        }

        _ => {
            path = path.join("Singles & EPs");

            let mut filename = title.to_string();

            if !featured.is_empty() {
                filename.push_str(" (feat. ");
                filename.push_str(&featured.join(", "));
                filename.push(')');
            }

            path.join(format!("{}.opus", sanitize_component(&filename)))
        }
    }
}

fn sanitize_component(s: &str) -> String {
    let mut out = String::new();
    for c in s.chars() {
        match c {
            '/' | '\\' | '\0' => out.push('_'),
            ':' => out.push('-'),
            '"' => out.push('\''),
            '*' | '?' | '<' | '>' | '|' => out.push('_'),
            _ => out.push(c),
        }
    }

    let trimmed = out.trim();
    if trimmed.is_empty() {
        "Unknown".to_string()
    } else {
        trimmed.to_string()
    }
}

fn move_file(src: &Path, dst: &Path) -> std::io::Result<()> {
    if dst.exists() {
        return Err(std::io::Error::new(
            std::io::ErrorKind::AlreadyExists,
            format!("destination already exists: {}", dst.display()),
        ));
    }

    match fs::rename(src, dst) {
        Ok(_) => Ok(()),

        Err(e) if e.raw_os_error() == Some(18) => {
            // EXDEV (errno 18) = cross-device link error
            fs::copy(src, dst)?;
            fs::remove_file(src)?;
            Ok(())
        }

        Err(e) => Err(e),
    }
}

// ==============================================================
// Inline Unit Tests
// ==============================================================

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::tempdir;

    /// Create a dummy file with a YouTube-style filename.
    fn dummy_track(dir: &std::path::Path, name: &str) -> std::path::PathBuf {
        let path = dir.join(name);
        fs::write(&path, b"not real audio").unwrap();
        path
    }

    #[test]
    fn classify_auto_generated_album() {
        let dir = tempdir().unwrap();
        let track = dummy_track(dir.path(), "EdEddnEddy [2BYqLgxoZRI].opus");

        // Fake minimal metadata by embedding it via exiftool is overkill here,
        // so for now this test only asserts classification logic *structure*.
        //
        // Later we’ll add metadata injection helpers if needed.

        let meta = crate::metadata::model::TrackMetadata {
            title: "EdEddnEddy".into(),
            artist: "JID".into(),
            album: Some("The Never Story".into()),
            duration_secs: 140.0,
            date: Some("2017-03-10".into()),
            track: None,
            purl: Some("https://www.youtube.com/watch?v=2BYqLgxoZRI".into()),
            comment: Some(
                "Provided to YouTube by Universal Music Group\nAuto-generated by YouTube.".into(),
            ),
            synopsis: None,
            confidence: crate::metadata::model::MetadataConfidence::Exact,
        };

        let kind = classify_track(&meta);
        assert_eq!(kind, TrackKind::AutoGeneratedAlbum);
    }

    #[test]
    fn classify_official_audio_single() {
        let meta = crate::metadata::model::TrackMetadata {
            title: "Some Song (Official Audio)".into(),
            artist: "Artist".into(),
            album: None,
            duration_secs: 200.0,
            date: None,
            track: None,
            purl: None,
            comment: None,
            synopsis: None,
            confidence: crate::metadata::model::MetadataConfidence::Exact,
        };

        let kind = classify_track(&meta);
        assert_eq!(kind, TrackKind::OfficialAudioSingle);
    }

    #[test]
    fn classify_creator_upload_fallback() {
        let meta = crate::metadata::model::TrackMetadata {
            title: "random upload".into(),
            artist: "someone".into(),
            album: None,
            duration_secs: 100.0,
            date: None,
            track: None,
            purl: None,
            comment: None,
            synopsis: None,
            confidence: crate::metadata::model::MetadataConfidence::Exact,
        };

        let kind = classify_track(&meta);
        assert_eq!(kind, TrackKind::CreatorUpload);
    }

    #[test]
    fn parses_family_ties_video() {
        let (title, feats) = normalize_title_and_features(
            "Baby Keem, Kendrick Lamar - family ties (Official Video)",
        );
        assert_eq!(title, "Baby Keem, Kendrick Lamar - family ties");
        assert!(feats.is_empty());
    }

    #[test]
    fn parses_eminem_fuel_feat_jid() {
        let (title, feats) =
            normalize_title_and_features("Eminem - Fuel (feat. JID) [Official Audio]");
        assert_eq!(title, "Eminem - Fuel");
        assert_eq!(feats, vec!["JID"]);
    }

    #[test]
    fn parses_community_with_multiple_features() {
        let (title, feats) = normalize_title_and_features(
            "JID - Community (with Clipse, Pusha T & Malice) (Official Video)",
        );
        assert_eq!(title, "JID - Community");
        assert_eq!(feats, vec!["Clipse", "Pusha T", "Malice"]);
    }

    #[test]
    fn album_track_path_is_correct() {
        let root = Path::new("/Music");

        let path = compute_destination_path(
            root,
            "JID",
            Some("The Never Story"),
            "EdEddnEddy",
            &[],
            TrackKind::AutoGeneratedAlbum,
            Some(2017),
            Some(1),
        );

        assert_eq!(
            path,
            Path::new("/Music/JID/2017 - The Never Story/01. EdEddnEddy.opus")
        );
    }

    #[test]
    fn single_with_features_path_is_correct() {
        let root = Path::new("/Music");

        let path = compute_destination_path(
            root,
            "Eminem",
            None,
            "Fuel",
            &vec!["JID".into()],
            TrackKind::OfficialAudioSingle,
            Some(2024),
            None,
        );

        assert_eq!(
            path,
            Path::new("/Music/Eminem/Singles & EPs/Fuel (feat. JID).opus")
        );
    }

    #[test]
    fn community_video_path_is_correct() {
        let root = Path::new("/Music");

        let path = compute_destination_path(
            root,
            "JID",
            None,
            "Community",
            &vec!["Clipse".into(), "Pusha T".into(), "Malice".into()],
            TrackKind::OfficialVideo,
            Some(2025),
            None,
        );

        assert_eq!(
            path,
            Path::new("/Music/JID/Singles & EPs/Community (feat. Clipse, Pusha T, Malice).opus")
        );
    }

    #[test]
    fn moves_file_into_destination() {
        use std::fs;
        use tempfile::tempdir;

        let tmp = tempdir().unwrap();
        let src_dir = tmp.path().join("src");
        let lib_dir = tmp.path().join("Music");

        fs::create_dir_all(&src_dir).unwrap();

        let src_file = src_dir.join("Fuel (feat. JID) [xVuYQCa9saw].opus");
        fs::write(&src_file, b"test audio").unwrap();

        // Minimal metadata stub
        let meta = crate::metadata::model::TrackMetadata {
            title: "Fuel (feat. JID)".into(),
            artist: "Eminem".into(),
            album: None,
            duration_secs: 200.0,
            date: Some("2024-01-01".into()),
            track: None,
            purl: Some("https://www.youtube.com/watch?v=xVuYQCa9saw".into()),
            comment: None,
            synopsis: None,
            confidence: crate::metadata::model::MetadataConfidence::Exact,
        };

        // Write metadata is skipped; we just assert movement logic
        let path = compute_destination_path(
            &lib_dir,
            "Eminem",
            None,
            "Fuel",
            &vec!["JID".into()],
            TrackKind::OfficialAudioSingle,
            Some(2024),
            None,
        );

        fs::create_dir_all(path.parent().unwrap()).unwrap();
        move_file(&src_file, &path).unwrap();

        assert!(path.exists());
        assert!(!src_file.exists());
    }
}
