//! Download normalization logic.
//!
//! This module is responsible for taking a freshly downloaded audio file
//! (typically from yt-dlp) and deterministically placing it into the
//! canonical music library structure.
//!
//! Design constraints:
//! - No UI logic
//! - No AppState access
//! - No network access
//! - Filesystem is the source of truth
//! - Deterministic behavior (no guesses)

use ::std::fs;
use std::path::{Path, PathBuf};

use crate::metadata;
use crate::metadata::model::{TrustedSearchMetadata, TrustedSearchMetadataScope};
use crate::metadata::parse::{extract_release_year, extract_track_number, extract_youtube_id};
use crate::metadata::write::write_clean_tags;

/// High-level classification of a downloaded track.
///
/// This determines how the track is normalized and where it is placed
/// in the filesystem.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TrackKind {
    /// Auto-generated album track
    ///
    /// Identified by trusted "Provided to YouTube by ..."
    /// or "Auto-generated by YouTube" markers.
    AutoGeneratedAlbum,

    /// Official audio release (single, visualizer, lyric video, etc.)
    OfficialAudioSingle,

    /// Official music video
    OfficialVideo,

    /// Creator / promotional / unknown upload
    CreatorUpload,

    /// Album track whose identity comes from trusted search metadata
    /// rather than embedded auto-generated markers.
    TrustedAlbumTrack,
}

/// Result of normalizing a downloaded track.
///
/// This struct describes the *final, canonical* interpretation
/// of the track after metadata normalization.
#[derive(Debug, Clone)]
#[allow(dead_code)]
pub struct NormalizedTrack {
    pub artist: String,
    pub album: Option<String>,
    pub title: String,
    pub featured_artists: Vec<String>,

    pub track_number: Option<u32>,
    pub year: Option<u32>,

    pub kind: TrackKind,
    pub youtube_id: String,

    /// Final absolute path on disk after normalization.
    pub final_path: PathBuf,
}

/// Normalize a freshly downloaded track into the canonical library structure.
///
/// Responsibilities (implemented in later steps):
/// - Read embedded metadata
/// - Classify track kind
/// - Normalize artist / title / features
/// - Determine final destination directory
/// - Move and rename the file
///
/// This function performs **no downloads** and **no UI updates**.
pub fn normalize_downloaded_track(
    path: &Path,
    library_root: &Path,
) -> Result<NormalizedTrack, Box<dyn std::error::Error>> {
    normalize_downloaded_track_with_sidecar(path, library_root, None)
}

pub fn normalize_downloaded_track_with_sidecar(
    path: &Path,
    library_root: &Path,
    search_metadata: Option<&TrustedSearchMetadata>,
) -> Result<NormalizedTrack, Box<dyn std::error::Error>> {
    // Step 1: extract metadata
    let mut meta = metadata::extract_metadata(path).ok_or_else(|| {
        std::io::Error::new(
            std::io::ErrorKind::InvalidData,
            "failed to extract metadata",
        )
    })?;

    // Step 2: apply trusted search metadata override before classification.
    let sidecar_applied = apply_search_metadata_override(&mut meta, search_metadata);

    // Step 3: extract stable identifiers
    let youtube_id = extract_youtube_id(&meta, path).ok_or_else(|| {
        std::io::Error::new(std::io::ErrorKind::InvalidData, "missing YouTube ID")
    })?;

    let track_number = extract_track_number(&meta, path);
    let year = extract_release_year(&meta);

    // Step 4: classify track kind
    let mut kind = classify_track(&meta);

    // Upgrade to album-path treatment only when the sidecar provides enough
    // identity — at least artist + album — so we don't place a weak embedded
    // artist into an album directory structure.
    if sidecar_applied
        && search_metadata.is_some_and(|s| s.artist.is_some() && s.album.is_some())
        && kind != TrackKind::AutoGeneratedAlbum
    {
        kind = TrackKind::TrustedAlbumTrack;
    }

    let comment_text = artist_comment_text(&meta, search_metadata);
    let (artist, mut featured_artists) = normalize_artist(comment_text, &meta.artist, &meta.title);
    let (title, title_features) = normalize_title_and_features(&meta.title);
    featured_artists.extend(title_features);

    let final_path = compute_destination_path(
        library_root,
        &artist,
        meta.album.as_deref(),
        &title,
        &featured_artists,
        kind,
        year,
        track_number,
    );

    // Ensure parent directories exist
    if let Some(parent) = final_path.parent() {
        std::fs::create_dir_all(parent)?;
    }

    // Perform the move
    move_file(path, &final_path)?;

    write_clean_tags(
        &final_path,
        &NormalizedTrack {
            artist: artist.clone(),
            album: meta.album.clone(),
            title: title.clone(),
            featured_artists: featured_artists.clone(),
            track_number,
            year,
            kind,
            youtube_id: youtube_id.clone(),
            final_path: final_path.clone(),
        },
    )?;

    Ok(NormalizedTrack {
        artist,
        album: meta.album.clone(),
        title,
        featured_artists,
        track_number,
        year,
        kind,
        youtube_id,
        final_path,
    })
}

fn classify_track(meta: &crate::metadata::model::TrackMetadata) -> TrackKind {
    let album_present = meta
        .album
        .as_deref()
        .map(|a| !a.trim().is_empty())
        .unwrap_or(false);

    let marker_text = meta
        .comment
        .as_deref()
        .or(meta.synopsis.as_deref())
        .unwrap_or("");

    // Trusted auto-generated album markers
    if album_present
        && (marker_text.contains("Provided to YouTube by")
            || marker_text.contains("Auto-generated by YouTube"))
    {
        return TrackKind::AutoGeneratedAlbum;
    }

    let title = meta.title.to_lowercase();

    if contains_any(
        &title,
        &["official audio", "visualizer", "lyric video", "lyrics"],
    ) {
        return TrackKind::OfficialAudioSingle;
    }

    if contains_any(&title, &["official video", "music video", " mv "]) {
        return TrackKind::OfficialVideo;
    }

    TrackKind::CreatorUpload
}

fn contains_any(haystack: &str, needles: &[&str]) -> bool {
    needles.iter().any(|n| haystack.contains(n))
}

fn has_autogenerated_markers(meta: &crate::metadata::model::TrackMetadata) -> bool {
    let marker_text = meta
        .comment
        .as_deref()
        .or(meta.synopsis.as_deref())
        .unwrap_or("");
    marker_text.contains("Provided to YouTube by")
        || marker_text.contains("Auto-generated by YouTube")
}

fn artist_comment_text<'a>(
    meta: &'a crate::metadata::model::TrackMetadata,
    search: Option<&TrustedSearchMetadata>,
) -> Option<&'a str> {
    let ignore_comment_artist = search.is_some_and(|search| {
        search.is_trusted
            && search.scope == TrustedSearchMetadataScope::Album
            && search.artist.is_some()
    });

    if ignore_comment_artist {
        None
    } else {
        meta.comment.as_deref().or(meta.synopsis.as_deref())
    }
}

/// Apply trusted search metadata to override weak embedded metadata.
///
/// Precedence:
/// 1. Embedded metadata with auto-generated markers is already trustworthy → no override.
/// 2. Trusted sidecar overrides weak/noisy embedded artist/title/album.
/// 3. No sidecar or untrusted sidecar → no override.
///
/// Returns true if any fields were overridden.
fn apply_search_metadata_override(
    meta: &mut crate::metadata::model::TrackMetadata,
    search: Option<&TrustedSearchMetadata>,
) -> bool {
    let Some(search) = search else {
        return false;
    };
    if !search.is_trusted {
        return false;
    }
    let has_markers = has_autogenerated_markers(meta);
    if has_markers && search.scope == TrustedSearchMetadataScope::Song {
        return false;
    }

    let mut applied = false;

    if let Some(track) = &search.track
        && (!has_markers || search.scope == TrustedSearchMetadataScope::Song)
    {
        meta.title = track.clone();
        applied = true;
    }
    if let Some(artist) = &search.artist {
        meta.artist = artist.clone();
        applied = true;
    }
    if search.album.is_some() {
        meta.album.clone_from(&search.album);
        applied = true;
    }

    applied
}

fn normalize_artist(comment: Option<&str>, raw: &str, title: &str) -> (String, Vec<String>) {
    // Priority 1: YouTube Music comment format — most reliable source.
    // The comment's first line is "Track Title · Artist1 · Artist2 · ..."
    // Artist1 is always the primary artist, regardless of what the artist tag says.
    if let Some(primary) = primary_artist_from_comment(comment) {
        return (primary, Vec::new());
    }

    // Priority 2: First comma-separated value from the artist tag.
    // Handles "Dr. Dre, Hittman, Snoop Dogg" → "Dr. Dre".
    // The convention in music metadata is that the primary artist is listed first.
    let raw = raw.trim();
    if let Some(primary) = raw
        .split(',')
        .next()
        .map(str::trim)
        .filter(|s| !s.is_empty())
        && !primary.ends_with("Music")
    {
        return (primary.to_string(), Vec::new());
    }

    // Priority 3: Generic YouTube channel placeholder — derive from title instead.
    if raw.ends_with("Music")
        && let Some(artist) = extract_artist_from_title(title)
    {
        return (artist, Vec::new());
    }

    (raw.to_string(), Vec::new())
}

/// Extract the primary artist from a YouTube Music comment/synopsis.
/// Format: "Track Title · Artist1 · Artist2 · ..."
fn primary_artist_from_comment(comment: Option<&str>) -> Option<String> {
    let first_line = comment?.lines().next()?.trim();
    if !first_line.contains(" · ") {
        return None;
    }
    let mut parts = first_line.split(" · ");
    parts.next(); // skip track title
    let primary = parts.next()?.trim();
    if primary.is_empty() {
        return None;
    }
    Some(primary.to_string())
}

fn extract_artist_from_title(title: &str) -> Option<String> {
    let parts: Vec<_> = title.splitn(2, " - ").collect();
    if parts.len() == 2 && !parts[0].trim().is_empty() {
        Some(parts[0].trim().to_string())
    } else {
        None
    }
}

fn normalize_title_and_features(raw: &str) -> (String, Vec<String>) {
    let mut title = raw.to_string();
    let mut features = Vec::new();

    // Strip leading "Artist - " if present
    if let Some((_, rest)) = title.split_once(" - ") {
        title = rest.to_string();
    }

    // (feat. X), (ft. X)
    if let Some((clean, feats)) = extract_features(&title, "feat.") {
        title = clean;
        features.extend(feats);
    }
    if let Some((clean, feats)) = extract_features(&title, "ft.") {
        title = clean;
        features.extend(feats);
    }

    // (with X, Y & Z)
    if let Some((clean, feats)) = extract_features(&title, "with") {
        title = clean;
        features.extend(feats);
    }

    // Strip junk suffixes AFTER feature extraction
    title = strip_junk_suffixes(&title);

    (title.trim().to_string(), dedup(features))
}

fn extract_features(title: &str, keyword: &str) -> Option<(String, Vec<String>)> {
    let lower = title.to_lowercase();
    let key = format!("({}", keyword);

    let start = lower.find(&key)?;
    let end = lower[start..].find(')')? + start;

    let inside = &title[start + key.len() + 1..end];
    let artists = split_artists(inside);

    let mut cleaned = String::new();
    cleaned.push_str(title[..start].trim_end());
    cleaned.push_str(title[end + 1..].trim_start());

    Some((cleaned, artists))
}

fn split_artists(s: &str) -> Vec<String> {
    s.split([',', '&'])
        .map(|a| a.trim())
        .filter(|a| !a.is_empty())
        .map(|a| a.to_string())
        .collect()
}

fn strip_junk_suffixes(title: &str) -> String {
    let junk = [
        "official video",
        "official audio",
        "visualizer",
        "lyrics",
        "high quality",
        "hq",
        "hd",
        "audio",
    ];

    let mut t = title.to_string();

    loop {
        let lower = t.to_lowercase();
        let mut removed = false;

        for j in junk {
            let pat = format!("({})", j);
            let pat2 = format!("[{}]", j);

            if lower.ends_with(&pat) {
                t = t[..t.len() - pat.len()].trim().to_string();
                removed = true;
            } else if lower.ends_with(&pat2) {
                t = t[..t.len() - pat2.len()].trim().to_string();
                removed = true;
            }
        }

        if !removed {
            break;
        }
    }

    t
}

fn dedup(list: Vec<String>) -> Vec<String> {
    let mut out = Vec::new();
    for a in list {
        if !out.iter().any(|x: &String| x.eq_ignore_ascii_case(&a)) {
            out.push(a);
        }
    }
    out
}

#[allow(clippy::too_many_arguments)]
fn compute_destination_path(
    library_root: &Path,
    artist: &str,
    album: Option<&str>,
    title: &str,
    featured: &[String],
    kind: TrackKind,
    year: Option<u32>,
    track_number: Option<u32>,
) -> PathBuf {
    let mut path = library_root.join(sanitize_component(artist));

    match kind {
        TrackKind::AutoGeneratedAlbum | TrackKind::TrustedAlbumTrack if album.is_some() => {
            let album_name = album.unwrap();
            let album_dir = match year {
                Some(y) => format!("{y} - {}", album_name),
                None => album_name.to_string(),
            };

            path = path.join(sanitize_component(&album_dir));

            let filename = match track_number {
                Some(n) => format!("{:02}. {}", n, title),
                None => title.to_string(),
            };

            path.join(format!("{}.opus", sanitize_component(&filename)))
        }

        _ => {
            path = path.join("Singles & EPs");

            let mut filename = title.to_string();

            if !featured.is_empty() {
                filename.push_str(" (feat. ");
                filename.push_str(&featured.join(", "));
                filename.push(')');
            }

            path.join(format!("{}.opus", sanitize_component(&filename)))
        }
    }
}

fn sanitize_component(s: &str) -> String {
    let mut out = String::new();
    for c in s.chars() {
        match c {
            '/' | '\\' | '\0' => out.push('_'),
            ':' => out.push('-'),
            '"' => out.push('\''),
            '*' | '?' | '<' | '>' | '|' => out.push('_'),
            _ => out.push(c),
        }
    }

    let trimmed = out.trim();
    if trimmed.is_empty() {
        "Unknown".to_string()
    } else {
        trimmed.to_string()
    }
}

fn move_file(src: &Path, dst: &Path) -> std::io::Result<()> {
    if dst.exists() {
        return Err(std::io::Error::new(
            std::io::ErrorKind::AlreadyExists,
            format!("destination already exists: {}", dst.display()),
        ));
    }

    match fs::rename(src, dst) {
        Ok(_) => Ok(()),

        Err(e) if e.raw_os_error() == Some(18) => {
            // EXDEV (errno 18) = cross-device link error
            fs::copy(src, dst)?;
            fs::remove_file(src)?;
            Ok(())
        }

        Err(e) => Err(e),
    }
}

// ==============================================================
// Inline Unit Tests
// ==============================================================

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;
    use tempfile::tempdir;

    /// Create a dummy file with a YouTube-style filename.
    fn dummy_track(dir: &std::path::Path, name: &str) -> std::path::PathBuf {
        let path = dir.join(name);
        fs::write(&path, b"not real audio").unwrap();
        path
    }

    #[test]
    fn comment_dot_format_extracts_primary_artist() {
        // YouTube Music comment: "Track · Dr. Dre · Hittman · Snoop Dogg\n..."
        let comment = "Bitch Niggaz · Dr. Dre · Hittman · Six-Two · Snoop Dogg\n\n2001";
        let (artist, _) = normalize_artist(
            Some(comment),
            "Dr. Dre, Hittman, Six-Two, Snoop Dogg",
            "Bitch Niggaz",
        );
        assert_eq!(artist, "Dr. Dre");
    }

    #[test]
    fn falls_back_to_first_comma_split_when_no_comment() {
        let (artist, _) = normalize_artist(None, "Jay Electronica, The-Dream", "Shiny Suit Theory");
        assert_eq!(artist, "Jay Electronica");
    }

    #[test]
    fn single_artist_unchanged() {
        let (artist, _) = normalize_artist(None, "Kendrick Lamar", "N95");
        assert_eq!(artist, "Kendrick Lamar");
    }

    #[test]
    fn classify_auto_generated_album() {
        let dir = tempdir().unwrap();
        let _track = dummy_track(dir.path(), "EdEddnEddy [2BYqLgxoZRI].opus");

        // Fake minimal metadata by embedding it via exiftool is overkill here,
        // so for now this test only asserts classification logic *structure*.
        //
        // Later we’ll add metadata injection helpers if needed.

        let meta = crate::metadata::model::TrackMetadata {
            album_artist: None,
            title: "EdEddnEddy".into(),
            artist: "JID".into(),
            album: Some("The Never Story".into()),
            duration_secs: 140.0,
            date: Some("2017-03-10".into()),
            track: None,
            purl: Some("https://www.youtube.com/watch?v=2BYqLgxoZRI".into()),
            comment: Some(
                "Provided to YouTube by Universal Music Group\nAuto-generated by YouTube.".into(),
            ),
            synopsis: None,
            confidence: crate::metadata::model::MetadataConfidence::Exact,
        };

        let kind = classify_track(&meta);
        assert_eq!(kind, TrackKind::AutoGeneratedAlbum);
    }

    #[test]
    fn classify_official_audio_single() {
        let meta = crate::metadata::model::TrackMetadata {
            album_artist: None,
            title: "Some Song (Official Audio)".into(),
            artist: "Artist".into(),
            album: None,
            duration_secs: 200.0,
            date: None,
            track: None,
            purl: None,
            comment: None,
            synopsis: None,
            confidence: crate::metadata::model::MetadataConfidence::Exact,
        };

        let kind = classify_track(&meta);
        assert_eq!(kind, TrackKind::OfficialAudioSingle);
    }

    #[test]
    fn classify_creator_upload_fallback() {
        let meta = crate::metadata::model::TrackMetadata {
            album_artist: None,
            title: "random upload".into(),
            artist: "someone".into(),
            album: None,
            duration_secs: 100.0,
            date: None,
            track: None,
            purl: None,
            comment: None,
            synopsis: None,
            confidence: crate::metadata::model::MetadataConfidence::Exact,
        };

        let kind = classify_track(&meta);
        assert_eq!(kind, TrackKind::CreatorUpload);
    }

    #[test]
    fn parses_family_ties_video() {
        let (title, feats) = normalize_title_and_features(
            "Baby Keem, Kendrick Lamar - family ties (Official Video)",
        );
        assert_eq!(title, "family ties");
        assert!(feats.is_empty());
    }

    #[test]
    fn parses_eminem_fuel_feat_jid() {
        let (title, feats) =
            normalize_title_and_features("Eminem - Fuel (feat. JID) [Official Audio]");
        assert_eq!(title, "Fuel");
        assert_eq!(feats, vec!["JID"]);
    }

    #[test]
    fn parses_community_with_multiple_features() {
        let (title, feats) = normalize_title_and_features(
            "JID - Community (with Clipse, Pusha T & Malice) (Official Video)",
        );
        assert_eq!(title, "Community");
        assert_eq!(feats, vec!["Clipse", "Pusha T", "Malice"]);
    }

    #[test]
    fn album_track_path_is_correct() {
        let root = Path::new("/Music");

        let path = compute_destination_path(
            root,
            "JID",
            Some("The Never Story"),
            "EdEddnEddy",
            &[],
            TrackKind::AutoGeneratedAlbum,
            Some(2017),
            Some(1),
        );

        assert_eq!(
            path,
            Path::new("/Music/JID/2017 - The Never Story/01. EdEddnEddy.opus")
        );
    }

    #[test]
    fn single_with_features_path_is_correct() {
        let root = Path::new("/Music");

        let path = compute_destination_path(
            root,
            "Eminem",
            None,
            "Fuel",
            &["JID".into()],
            TrackKind::OfficialAudioSingle,
            Some(2024),
            None,
        );

        assert_eq!(
            path,
            Path::new("/Music/Eminem/Singles & EPs/Fuel (feat. JID).opus")
        );
    }

    #[test]
    fn community_video_path_is_correct() {
        let root = Path::new("/Music");

        let path = compute_destination_path(
            root,
            "JID",
            None,
            "Community",
            &["Clipse".into(), "Pusha T".into(), "Malice".into()],
            TrackKind::OfficialVideo,
            Some(2025),
            None,
        );

        assert_eq!(
            path,
            Path::new("/Music/JID/Singles & EPs/Community (feat. Clipse, Pusha T, Malice).opus")
        );
    }

    #[test]
    fn moves_file_into_destination() {
        use std::fs;
        use tempfile::tempdir;

        let tmp = tempdir().unwrap();
        let src_dir = tmp.path().join("src");
        let lib_dir = tmp.path().join("Music");

        fs::create_dir_all(&src_dir).unwrap();

        let src_file = src_dir.join("Fuel (feat. JID) [xVuYQCa9saw].opus");
        fs::write(&src_file, b"test audio").unwrap();

        // Minimal metadata stub
        let _meta = crate::metadata::model::TrackMetadata {
            album_artist: None,
            title: "Fuel (feat. JID)".into(),
            artist: "Eminem".into(),
            album: None,
            duration_secs: 200.0,
            date: Some("2024-01-01".into()),
            track: None,
            purl: Some("https://www.youtube.com/watch?v=xVuYQCa9saw".into()),
            comment: None,
            synopsis: None,
            confidence: crate::metadata::model::MetadataConfidence::Exact,
        };

        // Write metadata is skipped; we just assert movement logic
        let path = compute_destination_path(
            &lib_dir,
            "Eminem",
            None,
            "Fuel",
            &["JID".into()],
            TrackKind::OfficialAudioSingle,
            Some(2024),
            None,
        );

        fs::create_dir_all(path.parent().unwrap()).unwrap();
        move_file(&src_file, &path).unwrap();

        assert!(path.exists());
        assert!(!src_file.exists());
    }

    // ---------------------------------------------------------------
    // Search metadata sidecar override tests
    // ---------------------------------------------------------------

    fn creator_upload_meta() -> crate::metadata::model::TrackMetadata {
        crate::metadata::model::TrackMetadata {
            album_artist: None,
            title: "Kanye West - Spaceship (High Quality)".into(),
            artist: "Red System Of U Day".into(),
            album: None,
            duration_secs: 325.0,
            date: None,
            track: None,
            purl: Some("https://www.youtube.com/watch?v=vYNT6LWoMJA".into()),
            comment: None,
            synopsis: None,
            confidence: crate::metadata::model::MetadataConfidence::Exact,
        }
    }

    fn autogenerated_album_meta() -> crate::metadata::model::TrackMetadata {
        crate::metadata::model::TrackMetadata {
            album_artist: None,
            title: "Spaceship".into(),
            artist: "Kanye West, GLC, Consequence".into(),
            album: Some("The College Dropout".into()),
            duration_secs: 324.0,
            date: Some("2004-02-10".into()),
            track: Some("12".into()),
            purl: Some("https://www.youtube.com/watch?v=ifinPSPUEF0".into()),
            comment: Some(
                "Provided to YouTube by Universal Music Group\n\nSpaceship · Kanye West · GLC · Consequence\n\nThe College Dropout\n\nReleased on: 2004-02-10\n\nAuto-generated by YouTube.".into(),
            ),
            synopsis: None,
            confidence: crate::metadata::model::MetadataConfidence::Exact,
        }
    }

    fn trusted_song_sidecar() -> TrustedSearchMetadata {
        TrustedSearchMetadata {
            track: Some("Spaceship".into()),
            artist: Some("Kanye West, GLC, Consequence".into()),
            album: Some("The College Dropout".into()),
            is_trusted: true,
            scope: TrustedSearchMetadataScope::Song,
        }
    }

    fn trusted_album_sidecar(artist: &str, album: &str) -> TrustedSearchMetadata {
        TrustedSearchMetadata {
            track: None,
            artist: Some(artist.into()),
            album: Some(album.into()),
            is_trusted: true,
            scope: TrustedSearchMetadataScope::Album,
        }
    }

    fn vultures_autogenerated_meta() -> crate::metadata::model::TrackMetadata {
        crate::metadata::model::TrackMetadata {
            album_artist: Some("Kanye West".into()),
            title: "FUK SUMN".into(),
            artist: "¥$, Kanye West, Ty Dolla $ign".into(),
            album: Some("VULTURES 1".into()),
            duration_secs: 230.0,
            date: Some("2024-02-10".into()),
            track: Some("5".into()),
            purl: Some("https://www.youtube.com/watch?v=example".into()),
            comment: Some(
                "Provided to YouTube by Label\n\nFUK SUMN · ¥$ · Kanye West · Ty Dolla $ign\n\nVULTURES 1\n\nReleased on: 2024-02-10\n\nAuto-generated by YouTube.".into(),
            ),
            synopsis: None,
            confidence: crate::metadata::model::MetadataConfidence::Exact,
        }
    }

    #[test]
    fn no_sidecar_keeps_existing_behavior() {
        let mut meta = creator_upload_meta();
        let applied = apply_search_metadata_override(&mut meta, None);

        assert!(!applied);
        assert_eq!(meta.artist, "Red System Of U Day");
        assert_eq!(meta.title, "Kanye West - Spaceship (High Quality)");
        assert_eq!(meta.album, None);
    }

    #[test]
    fn untrusted_sidecar_keeps_existing_behavior() {
        let mut meta = creator_upload_meta();
        let sidecar = TrustedSearchMetadata {
            is_trusted: false,
            ..trusted_song_sidecar()
        };
        let applied = apply_search_metadata_override(&mut meta, Some(&sidecar));

        assert!(!applied);
        assert_eq!(meta.artist, "Red System Of U Day");
        assert_eq!(meta.title, "Kanye West - Spaceship (High Quality)");
        assert_eq!(meta.album, None);
    }

    #[test]
    fn trusted_sidecar_overrides_creator_upload() {
        let mut meta = creator_upload_meta();
        let sidecar = trusted_song_sidecar();
        let applied = apply_search_metadata_override(&mut meta, Some(&sidecar));

        assert!(applied);
        assert_eq!(meta.artist, "Kanye West, GLC, Consequence");
        assert_eq!(meta.title, "Spaceship");
        assert_eq!(meta.album.as_deref(), Some("The College Dropout"));
    }

    #[test]
    fn autogenerated_not_clobbered_by_sidecar() {
        let mut meta = autogenerated_album_meta();
        let original_artist = meta.artist.clone();
        let original_title = meta.title.clone();
        let original_album = meta.album.clone();
        let sidecar = trusted_song_sidecar();
        let applied = apply_search_metadata_override(&mut meta, Some(&sidecar));

        assert!(!applied);
        assert_eq!(meta.artist, original_artist);
        assert_eq!(meta.title, original_title);
        assert_eq!(meta.album, original_album);
    }

    #[test]
    fn regression_creator_upload_with_sidecar_produces_album_path() {
        let root = Path::new("/Music");
        let mut meta = creator_upload_meta();
        let sidecar = trusted_song_sidecar();
        let sidecar_applied = apply_search_metadata_override(&mut meta, Some(&sidecar));

        let mut kind = classify_track(&meta);
        if sidecar_applied
            && sidecar.artist.is_some()
            && sidecar.album.is_some()
            && kind != TrackKind::AutoGeneratedAlbum
        {
            kind = TrackKind::TrustedAlbumTrack;
        }

        let comment_text = artist_comment_text(&meta, Some(&sidecar));
        let (artist, mut featured_artists) =
            normalize_artist(comment_text, &meta.artist, &meta.title);
        let (title, title_features) = normalize_title_and_features(&meta.title);
        featured_artists.extend(title_features);

        let year = crate::metadata::parse::extract_release_year(&meta);

        let path = compute_destination_path(
            root,
            &artist,
            meta.album.as_deref(),
            &title,
            &featured_artists,
            kind,
            year,
            None,
        );

        assert_eq!(artist, "Kanye West");
        assert_eq!(title, "Spaceship");
        assert_eq!(kind, TrackKind::TrustedAlbumTrack);
        assert_eq!(
            path,
            Path::new("/Music/Kanye West/The College Dropout/Spaceship.opus")
        );
    }

    #[test]
    fn autogenerated_track_without_sidecar_keeps_album_path() {
        let root = Path::new("/Music");
        let meta = autogenerated_album_meta();

        let kind = classify_track(&meta);
        let comment_text = meta.comment.as_deref().or(meta.synopsis.as_deref());
        let (artist, mut featured_artists) =
            normalize_artist(comment_text, &meta.artist, &meta.title);
        let (title, title_features) = normalize_title_and_features(&meta.title);
        featured_artists.extend(title_features);

        let year = crate::metadata::parse::extract_release_year(&meta);
        let track_number = meta.track.as_deref().and_then(|t| t.parse::<u32>().ok());

        let path = compute_destination_path(
            root,
            &artist,
            meta.album.as_deref(),
            &title,
            &featured_artists,
            kind,
            year,
            track_number,
        );

        assert_eq!(artist, "Kanye West");
        assert_eq!(title, "Spaceship");
        assert_eq!(kind, TrackKind::AutoGeneratedAlbum);
        assert_eq!(
            path,
            Path::new("/Music/Kanye West/2004 - The College Dropout/12. Spaceship.opus")
        );
    }

    #[test]
    fn creator_upload_without_sidecar_goes_to_singles() {
        let root = Path::new("/Music");
        let meta = creator_upload_meta();

        let kind = classify_track(&meta);
        let comment_text = meta.comment.as_deref().or(meta.synopsis.as_deref());
        let (artist, mut featured_artists) =
            normalize_artist(comment_text, &meta.artist, &meta.title);
        let (title, title_features) = normalize_title_and_features(&meta.title);
        featured_artists.extend(title_features);

        let path = compute_destination_path(
            root,
            &artist,
            meta.album.as_deref(),
            &title,
            &featured_artists,
            kind,
            None,
            None,
        );

        assert_eq!(kind, TrackKind::CreatorUpload);
        assert_eq!(artist, "Red System Of U Day");
        assert_eq!(title, "Spaceship");
        assert_eq!(
            path,
            Path::new("/Music/Red System Of U Day/Singles & EPs/Spaceship.opus")
        );
    }

    #[test]
    fn trusted_sidecar_without_album_keeps_singles_path() {
        let root = Path::new("/Music");
        let mut meta = creator_upload_meta();
        let sidecar = TrustedSearchMetadata {
            track: Some("Spaceship".into()),
            artist: Some("Kanye West".into()),
            album: None,
            is_trusted: true,
            scope: TrustedSearchMetadataScope::Song,
        };
        let sidecar_applied = apply_search_metadata_override(&mut meta, Some(&sidecar));

        let mut kind = classify_track(&meta);
        if sidecar_applied
            && sidecar.artist.is_some()
            && sidecar.album.is_some()
            && kind != TrackKind::AutoGeneratedAlbum
        {
            kind = TrackKind::TrustedAlbumTrack;
        }

        let comment_text = artist_comment_text(&meta, Some(&sidecar));
        let (artist, mut featured_artists) =
            normalize_artist(comment_text, &meta.artist, &meta.title);
        let (title, title_features) = normalize_title_and_features(&meta.title);
        featured_artists.extend(title_features);

        let path = compute_destination_path(
            root,
            &artist,
            meta.album.as_deref(),
            &title,
            &featured_artists,
            kind,
            None,
            None,
        );

        assert_eq!(artist, "Kanye West");
        assert_eq!(title, "Spaceship");
        assert_eq!(kind, TrackKind::CreatorUpload);
        assert_eq!(
            path,
            Path::new("/Music/Kanye West/Singles & EPs/Spaceship.opus")
        );
    }

    #[test]
    fn partial_sidecar_with_album_but_no_artist_stays_singles() {
        let root = Path::new("/Music");
        let mut meta = creator_upload_meta();
        let sidecar = TrustedSearchMetadata {
            track: Some("Spaceship".into()),
            artist: None,
            album: Some("The College Dropout".into()),
            is_trusted: true,
            scope: TrustedSearchMetadataScope::Song,
        };
        let sidecar_applied = apply_search_metadata_override(&mut meta, Some(&sidecar));
        assert!(sidecar_applied);

        let mut kind = classify_track(&meta);
        if sidecar_applied
            && sidecar.artist.is_some()
            && sidecar.album.is_some()
            && kind != TrackKind::AutoGeneratedAlbum
        {
            kind = TrackKind::TrustedAlbumTrack;
        }

        let comment_text = artist_comment_text(&meta, Some(&sidecar));
        let (artist, mut featured_artists) =
            normalize_artist(comment_text, &meta.artist, &meta.title);
        let (title, title_features) = normalize_title_and_features(&meta.title);
        featured_artists.extend(title_features);

        let path = compute_destination_path(
            root,
            &artist,
            meta.album.as_deref(),
            &title,
            &featured_artists,
            kind,
            None,
            None,
        );

        // Artist is still the weak embedded value because sidecar had no artist.
        // Kind should NOT be upgraded to TrustedAlbumTrack.
        assert_eq!(kind, TrackKind::CreatorUpload);
        assert_eq!(artist, "Red System Of U Day");
        assert_eq!(title, "Spaceship");
        assert_eq!(
            path,
            Path::new("/Music/Red System Of U Day/Singles & EPs/Spaceship.opus")
        );
    }

    // ---------------------------------------------------------------
    // Junk-suffix stripping tests
    // ---------------------------------------------------------------

    #[test]
    fn strips_high_quality_suffix() {
        let (title, feats) = normalize_title_and_features("Kanye West - Spaceship (High Quality)");
        assert_eq!(title, "Spaceship");
        assert!(feats.is_empty());
    }

    #[test]
    fn strips_hq_suffix() {
        let (title, _) = normalize_title_and_features("Song Title (HQ)");
        assert_eq!(title, "Song Title");
    }

    #[test]
    fn strips_hd_suffix_in_brackets() {
        let (title, _) = normalize_title_and_features("Song Title [HD]");
        assert_eq!(title, "Song Title");
    }

    #[test]
    fn strips_audio_suffix() {
        let (title, _) = normalize_title_and_features("Song Title (Audio)");
        assert_eq!(title, "Song Title");
    }

    #[test]
    fn strips_multiple_junk_suffixes_iteratively() {
        let (title, _) = normalize_title_and_features("Song Title (Official Video) (HQ)");
        assert_eq!(title, "Song Title");
    }

    #[test]
    fn preserves_remastered_suffix() {
        let (title, _) = normalize_title_and_features("Song Title (Remastered)");
        assert_eq!(title, "Song Title (Remastered)");
    }

    #[test]
    fn existing_official_audio_stripping_still_works() {
        let (title, _) = normalize_title_and_features("Song Title (Official Audio)");
        assert_eq!(title, "Song Title");
    }

    #[test]
    fn existing_lyrics_stripping_still_works() {
        let (title, _) = normalize_title_and_features("Song Title [Lyrics]");
        assert_eq!(title, "Song Title");
    }

    // ---------------------------------------------------------------
    // Album-level sidecar (preview download) tests
    // ---------------------------------------------------------------

    #[test]
    fn album_sidecar_without_track_preserves_embedded_title() {
        let mut meta = crate::metadata::model::TrackMetadata {
            album_artist: None,
            title: "Shiny Suit Theory".into(),
            artist: "Jay Electronica, The-Dream".into(),
            album: None,
            duration_secs: 240.0,
            date: None,
            track: None,
            purl: None,
            comment: None,
            synopsis: None,
            confidence: crate::metadata::model::MetadataConfidence::Exact,
        };

        let sidecar = trusted_album_sidecar("Jay Electronica", "A Written Testimony");

        let applied = apply_search_metadata_override(&mut meta, Some(&sidecar));

        assert!(applied);
        assert_eq!(meta.title, "Shiny Suit Theory");
        assert_eq!(meta.artist, "Jay Electronica");
        assert_eq!(meta.album.as_deref(), Some("A Written Testimony"));
    }

    #[test]
    fn album_sidecar_without_track_files_to_album_directory() {
        let root = Path::new("/Music");
        let mut meta = crate::metadata::model::TrackMetadata {
            album_artist: None,
            title: "Shiny Suit Theory".into(),
            artist: "Jay Electronica, The-Dream".into(),
            album: None,
            duration_secs: 240.0,
            date: None,
            track: None,
            purl: None,
            comment: None,
            synopsis: None,
            confidence: crate::metadata::model::MetadataConfidence::Exact,
        };

        let sidecar = trusted_album_sidecar("Jay Electronica", "A Written Testimony");

        let sidecar_applied = apply_search_metadata_override(&mut meta, Some(&sidecar));

        let mut kind = classify_track(&meta);
        if sidecar_applied
            && sidecar.artist.is_some()
            && sidecar.album.is_some()
            && kind != TrackKind::AutoGeneratedAlbum
        {
            kind = TrackKind::TrustedAlbumTrack;
        }

        let comment_text = artist_comment_text(&meta, Some(&sidecar));
        let (artist, mut featured_artists) =
            normalize_artist(comment_text, &meta.artist, &meta.title);
        let (title, title_features) = normalize_title_and_features(&meta.title);
        featured_artists.extend(title_features);

        let path = compute_destination_path(
            root,
            &artist,
            meta.album.as_deref(),
            &title,
            &featured_artists,
            kind,
            None,
            None,
        );

        assert_eq!(kind, TrackKind::TrustedAlbumTrack);
        assert_eq!(artist, "Jay Electronica");
        assert_eq!(title, "Shiny Suit Theory");
        assert_eq!(
            path,
            Path::new("/Music/Jay Electronica/A Written Testimony/Shiny Suit Theory.opus")
        );
    }

    #[test]
    fn album_sidecar_overrides_autogenerated_artist_for_consistent_album_filing() {
        let root = Path::new("/Music");
        let mut meta = vultures_autogenerated_meta();
        let sidecar = trusted_album_sidecar("Kanye West", "VULTURES 1");

        let sidecar_applied = apply_search_metadata_override(&mut meta, Some(&sidecar));

        let mut kind = classify_track(&meta);
        if sidecar_applied
            && sidecar.artist.is_some()
            && sidecar.album.is_some()
            && kind != TrackKind::AutoGeneratedAlbum
        {
            kind = TrackKind::TrustedAlbumTrack;
        }

        let comment_text = artist_comment_text(&meta, Some(&sidecar));
        let (artist, mut featured_artists) =
            normalize_artist(comment_text, &meta.artist, &meta.title);
        let (title, title_features) = normalize_title_and_features(&meta.title);
        featured_artists.extend(title_features);

        let year = crate::metadata::parse::extract_release_year(&meta);
        let track_number = meta.track.as_deref().and_then(|t| t.parse::<u32>().ok());

        let path = compute_destination_path(
            root,
            &artist,
            meta.album.as_deref(),
            &title,
            &featured_artists,
            kind,
            year,
            track_number,
        );

        assert!(sidecar_applied);
        assert_eq!(kind, TrackKind::AutoGeneratedAlbum);
        assert_eq!(artist, "Kanye West");
        assert_eq!(title, "FUK SUMN");
        assert_eq!(
            path,
            Path::new("/Music/Kanye West/2024 - VULTURES 1/05. FUK SUMN.opus")
        );
    }
}
